"""update updates post model

Revision ID: d186681f63f7
Revises: cd3d15303b5e
Create Date: 2026-09-05 11:44:26.309552

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd186681f63f7'
down_revision = 'cd3d15303b5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
  
    with op.batch_alter_table('updates_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emoji_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('media_url', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('media_type', sa.String(length=10), nullable=False))
        batch_op.create_foreign_key(None, 'emoji', ['emoji_id'], ['id'])
        batch_op.drop_column('video_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('updates_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('media_type')
        batch_op.drop_column('media_url')
        batch_op.drop_column('emoji_id')

    op.create_table('explore_post',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('video_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'ready'::character varying"), autoincrement=False, nullable=False),
    sa.Column('cloudinary_public_id', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('explore_post_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('explore_post_pkey'))
    )
    # ### end Alembic commands ###
